# Generated by Django 2.2.5 on 2021-05-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=50, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('active_stamp', models.BooleanField()),
                ('olx_stamp', models.BooleanField()),
                ('price', models.PositiveIntegerField()),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True, db_index=True, max_length=1000)),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
