# Generated by Django 2.2.5 on 2021-05-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouses',
            name='products',
            field=models.ManyToManyField(related_name='related_products', to='warehouse.Product'),
        ),
    ]
