# Generated by Django 2.2.5 on 2020-09-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_post_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lang_filter',
            field=models.CharField(blank=True, choices=[('Polski', 'PL'), ('Russian', 'RU')], default='RU', max_length=2, verbose_name='Site side: '),
        ),
    ]
