# Generated by Django 2.2.5 on 2020-10-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_lang_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='Likes'),
        ),
        migrations.AlterField(
            model_name='post',
            name='lang_filter',
            field=models.CharField(blank=True, choices=[('PL', 'Polski'), ('RU', 'Russian')], default='RU', max_length=2, verbose_name='Site side: '),
        ),
    ]
