# Generated by Django 2.2.5 on 2020-10-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201006_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, db_index=True, max_length=500, verbose_name='Preview'),
        ),
    ]
