# Generated by Django 2.2.5 on 2020-11-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201104_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='related_post',
            field=models.ManyToManyField(blank=True, related_name='_post_related_post_+', to='blog.Post'),
        ),
    ]
